version: "3.9"  # optional since v1.27.0
services:
  pokegen_torchserve:
    environment: 
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    build: .
    networks:
      - traefik_proxy
    expose:
      - 8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pokegen_server.rule=Host(`${DOMAIN_URL}`)"
      - "traefik.http.routers.pokegen_server.service=pokegen_server"
      - "traefik.http.routers.pokegen_server.entrypoints=http"


networks:
    traefik_proxy:
        external:
            name: "traefik_proxy"