version: "3.9"
    
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: ${DB_PASSWORD}
    expose:
      - 3306 
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pokegen_hyper_db.rule=HostSNI(`${DB_URL}`)"
      - "traefik.http.routers.pokegen_hyper_db.entrypoints=websecure"
      - "traefik.http.routers.pokegen_hyper_db.tls.certresolver=sql"
      - "traefik.tcp.services.pokegen_hyper_db.loadbalancer.server.port=3306"
    
networks:
    traefik_proxy:
        external:
            name: "traefik_proxy"