version: "3.9"  # optional since v1.27.0
services:
  pokegen:
    restart: always
    environment: 
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    build: 
      context: ..
      dockerfile: demo/Dockerfile
    networks:
      - proxynet
    expose:
      - 8501
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pokegen_demo.rule=Host(`${DOMAIN_URL}`)"
      - "traefik.http.routers.pokegen_demo.entrypoints=http"
      # - "traefik.http.routers.pokegen_demo.tls.certresolver=myresolver"

networks:
    proxynet:
        external:
            name: "proxynet"
