# This is a basic workflow to help you get started with Actions

name: VAE Hypers

# Controls when the action will run. 
on:
  workflow_dispatch:
    inputs:
      duration:
        description: "Number of seconds to run on each runner"
        required: true
        default: 7200 # 2 hours

concurrency: hyper

jobs:
  setup_sql:
    runs-on: [self-hosted,ec2-micro,deploy]
    timeout-minutes: 10
    env: 
      DB_URL: ${{ secrets.DB_URL }}
      # TODO swap this for random value
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: deploy
        run: docker-compose -f hyper/docker-compose.yaml up --build -d
  
  down_sql:
    if: always()
    needs: [setup_sql, sweeper]
    runs-on: [self-hosted,ec2-micro,deploy]
    timeout-minutes: 10
    env: 
      DB_URL: ${{ secrets.DB_URL }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: deploy
        run: docker-compose -f hyper/docker-compose.yaml down --remove-orphans

  sweeper:
    needs: setup_sql
    runs-on: [self-hosted,gpu,training]
    timeout-minutes: 1440  # Increased job runtime since ML is slow
    strategy:
      fail-fast: false
      matrix:
        _: [1, 2, 3] # 3 gpu runners available

    container:
      image: etheredgeb/pokegen:cicd
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.MINIO_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.MINIO_AWS_SECRET_ACCESS_KEY }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        SHOULD_TQDM: 0  # disables tqdm in 'src/train_ae.py'
        DB_URL: ${{ secrets.DB_URL }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      options: --gpus all --shm-size=1G

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }} # https://github.com/stefanzweifel/git-auto-commit-action

      - name: Install as local package
        run: pip install -e .

      - name: pull_data
        run: dvc pull data/external/sprites.dvc

      - name: pull_repros
        continue-on-error: true
        run: dvc pull --run-cache train@vae

      - name: hyper
        run: |
          git config --global user.name "Benjamin Etheredge"
          git config --global user.email "benjamin.etheredge@gmail.com"
          python src/hyper/run.py vae ${{ github.event.inputs.duration }} best.yaml

      - name: report
        run: |
          cat best.yaml > report.md
          cml-send-github-check report.md 
      # TODO retrain with best params (dvc will maybe have it in cache)
      # check in dvc.lock with latest run
          
